import * as React from "react";
import DataTable from "../Components/DataTable";
import { assessmentType } from "../Helpers/AssessmentHelper";
import { fetchAllAssessments } from "../Helpers/AssessmentHelper";
import { useAuth0 } from "@auth0/auth0-react";
import AssessmentsGUI from "../Components/AssessmentGUI";

export default function AssessmentsScreen() {
  const [assessments, setAssessments] = React.useState<assessmentType[]>([
    {
      StudentID: 1,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Powers",
      Date: "2023-07-14",
      Points: 90,
      Comments: "Good work!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 1,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Powers",
      Date: "2023-10-14",
      Points: 88,
      Comments: "Good work!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 1,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Powers",
      Date: "2024-02-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 1,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Powers",
      Date: "2024-05-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 1,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Powers",
      Date: "2024-07-14",
      Points: 94,
      Comments: "Good work!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 2,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Powers",
      Date: "2023-07-14",
      Points: 85,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 2,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Powers",
      Date: "2023-10-14",
      Points: 82,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 2,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Powers",
      Date: "2024-02-14",
      Points: 83,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 2,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Powers",
      Date: "2024-05-14",
      Points: 80,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 2,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Powers",
      Date: "2024-07-14",
      Points: 84,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 3,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Powers",
      Date: "2023-07-14",
      Points: 95,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 3,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Powers",
      Date: "2023-10-14",
      Points: 90,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 3,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Powers",
      Date: "2024-02-14",
      Points: 98,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 3,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Powers",
      Date: "2024-05-14",
      Points: 97,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 3,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Powers",
      Date: "2024-07-14",
      Points: 96,
      Comments: "Excellent!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 4,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Powers",
      Date: "2023-07-14",
      Points: 88,
      Comments: "Well done",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 4,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Powers",
      Date: "2023-10-14",
      Points: 85,
      Comments: "Well done",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 4,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Powers",
      Date: "2024-02-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 4,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Powers",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 4,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Powers",
      Date: "2024-07-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 5,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Powers",
      Date: "2023-07-14",
      Points: 92,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 5,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Powers",
      Date: "2023-10-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 5,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Powers",
      Date: "2024-02-14",
      Points: 94,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 5,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Powers",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 5,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Powers",
      Date: "2024-07-14",
      Points: 92,
      Comments: "Keep it up",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 6,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Miller",
      Date: "2023-07-14",
      Points: 90,
      Comments: "Good work!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 6,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Miller",
      Date: "2023-10-14",
      Points: 88,
      Comments: "Good work!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 6,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Miller",
      Date: "2024-02-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 6,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Miller",
      Date: "2024-05-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 6,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Miller",
      Date: "2024-07-14",
      Points: 99,
      Comments: "Good work!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 7,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Miller",
      Date: "2023-07-14",
      Points: 85,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 7,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Miller",
      Date: "2023-10-14",
      Points: 82,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 7,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Miller",
      Date: "2024-02-14",
      Points: 83,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 7,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Miller",
      Date: "2024-05-14",
      Points: 80,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 7,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Miller",
      Date: "2024-07-14",
      Points: 78,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 8,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Miller",
      Date: "2023-07-14",
      Points: 95,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 8,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Miller",
      Date: "2023-10-14",
      Points: 90,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 8,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Miller",
      Date: "2024-02-14",
      Points: 98,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 8,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Miller",
      Date: "2024-05-14",
      Points: 97,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 8,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Miller",
      Date: "2024-07-14",
      Points: 99,
      Comments: "Excellent!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 9,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Miller",
      Date: "2023-07-14",
      Points: 88,
      Comments: "Well done",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 9,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Miller",
      Date: "2023-10-14",
      Points: 85,
      Comments: "Well done",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 9,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Miller",
      Date: "2024-02-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 9,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Miller",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 9,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Miller",
      Date: "2024-07-14",
      Points: 88,
      Comments: "Well done",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 10,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Miller",
      Date: "2023-07-14",
      Points: 92,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 10,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Miller",
      Date: "2023-10-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 10,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Miller",
      Date: "2024-02-14",
      Points: 94,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 10,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Miller",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 10,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Miller",
      Date: "2024-07-14",
      Points: 92,
      Comments: "Keep it up",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 11,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Davis",
      Date: "2023-07-14",
      Points: 90,
      Comments: "Good work!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 11,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Davis",
      Date: "2023-10-14",
      Points: 88,
      Comments: "Good work!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 11,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Davis",
      Date: "2024-02-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 11,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Davis",
      Date: "2024-05-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 11,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Davis",
      Date: "2024-07-14",
      Points: 100,
      Comments: "Good work!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 12,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Davis",
      Date: "2023-07-14",
      Points: 85,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 12,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Davis",
      Date: "2023-10-14",
      Points: 82,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 12,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Davis",
      Date: "2024-02-14",
      Points: 83,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 12,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Davis",
      Date: "2024-05-14",
      Points: 80,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 12,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Davis",
      Date: "2024-07-14",
      Points: 73,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 13,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Davis",
      Date: "2023-07-14",
      Points: 95,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 13,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Davis",
      Date: "2023-10-14",
      Points: 90,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 13,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Davis",
      Date: "2024-02-14",
      Points: 98,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 13,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Davis",
      Date: "2024-05-14",
      Points: 97,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 13,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Davis",
      Date: "2024-07-14",
      Points: 95,
      Comments: "Excellent!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 14,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Davis",
      Date: "2023-07-14",
      Points: 88,
      Comments: "Well done",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 14,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Davis",
      Date: "2023-10-14",
      Points: 85,
      Comments: "Well done",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 14,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Davis",
      Date: "2024-02-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 14,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Davis",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 14,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Davis",
      Date: "2024-07-14",
      Points: 90,
      Comments: "Well done",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 15,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Davis",
      Date: "2023-07-14",
      Points: 92,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 15,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Davis",
      Date: "2023-10-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 15,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Davis",
      Date: "2024-02-14",
      Points: 94,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 15,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Davis",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 15,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Davis",
      Date: "2024-07-14",
      Points: 97,
      Comments: "Keep it up",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 16,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Taylor",
      Date: "2023-07-14",
      Points: 90,
      Comments: "Good work!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 16,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Taylor",
      Date: "2023-10-14",
      Points: 88,
      Comments: "Good work!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 16,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Taylor",
      Date: "2024-02-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 16,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Taylor",
      Date: "2024-05-14",
      Points: 91,
      Comments: "Good work!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 16,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Taylor",
      Date: "2024-07-14",
      Points: 97,
      Comments: "Good work!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 17,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Taylor",
      Date: "2023-07-14",
      Points: 85,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 17,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Taylor",
      Date: "2023-10-14",
      Points: 82,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 17,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Taylor",
      Date: "2024-02-14",
      Points: 83,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 17,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Taylor",
      Date: "2024-05-14",
      Points: 80,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 17,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Taylor",
      Date: "2024-07-14",
      Points: 79,
      Comments: "Needs improvement",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 18,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Taylor",
      Date: "2023-07-14",
      Points: 95,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 18,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Taylor",
      Date: "2023-10-14",
      Points: 90,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 18,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Taylor",
      Date: "2024-02-14",
      Points: 98,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 18,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Taylor",
      Date: "2024-05-14",
      Points: 97,
      Comments: "Excellent!",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 18,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Taylor",
      Date: "2024-07-14",
      Points: 92,
      Comments: "Excellent!",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 19,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Taylor",
      Date: "2023-07-14",
      Points: 88,
      Comments: "Well done",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 19,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Taylor",
      Date: "2023-10-14",
      Points: 85,
      Comments: "Well done",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 19,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Taylor",
      Date: "2024-02-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 19,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Taylor",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Well done",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 19,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Taylor",
      Date: "2024-07-14",
      Points: 99,
      Comments: "Well done",
      Criterion: "How would you rate the students final project",
    },
    {
      StudentID: 20,
      RubricName: "Semester 1 Rubric",
      Facilitator: "Taylor",
      Date: "2023-07-14",
      Points: 92,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 1st project?",
    },
    {
      StudentID: 20,
      RubricName: "Semester 2 Rubric",
      Facilitator: "Taylor",
      Date: "2023-10-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 2nd project?",
    },
    {
      StudentID: 20,
      RubricName: "Semester 3 Rubric",
      Facilitator: "Taylor",
      Date: "2024-02-14",
      Points: 94,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 3rd project?",
    },
    {
      StudentID: 20,
      RubricName: "Semester 4 Rubric",
      Facilitator: "Taylor",
      Date: "2024-05-14",
      Points: 89,
      Comments: "Keep it up",
      Criterion: "How would you rate the students 4th project?",
    },
    {
      StudentID: 20,
      RubricName: "Semester 5 Rubric",
      Facilitator: "Taylor",
      Date: "2024-07-14",
      Points: 91,
      Comments: "Keep it up",
      Criterion: "How would you rate the students final project",
    },
  ]);
  const { getAccessTokenSilently } = useAuth0();
  React.useEffect(() => {
    const fetchRubrics = async () => {
      // try {
      //   const token = await getAccessTokenSilently({
      //     authorizationParams: {
      //       audience: `https://auth0-jwt-authorizer`,
      //     },
      //   });
      //   console.log(token);
      //   const assessments = await fetchAllAssessments(token);
      //   setAssessments(assessments);
      // } catch (e) {
      //   console.error(e);
      // }
    };
    fetchRubrics();
  }, [getAccessTokenSilently]);

  const studentIds: number[] = Array.from(
    new Set(assessments.map((item) => item.StudentID))
  );

  const facilitators: string[] = Array.from(
    new Set(assessments.map((item) => item.Facilitator))
  );
  return (
    <div>
      <h1 style={{ textAlign: "center" }}>Assessments GUI</h1>
      <AssessmentsGUI studentIds={studentIds} facilitators={facilitators} />
      <h1 style={{ textAlign: "center" }}>Assessments Database Table</h1>
      <DataTable
        labels={[
          "StudentID",
          "RubricName",
          "Facilitator",
          "Date",
          "Points",
          "Comments",
          "Criterion",
        ]}
        rows={assessments !== undefined ? assessments : []}
      />
    </div>
  );
}
